# Generated by Django 5.0.6 on 2024-06-12 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ServiceClient",
            new_name="Client",
        ),
    ]
