# Generated by Django 5.0.6 on 2024-06-14 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0002_rename_serviceclient_client"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mailingsettings",
            name="client",
        ),
        migrations.AddField(
            model_name="mailingsettings",
            name="client",
            field=models.ManyToManyField(to="mailings.client", verbose_name="клиент"),
        ),
    ]
