# Generated by Django 4.2 on 2024-07-15 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0005_client_owner_mailingsettings_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailingsettings",
            options={
                "permissions": [
                    ("deactivate_mailing", "Can deactivate mailing"),
                    ("view_all_mailings", "Can view all mailings"),
                ],
                "verbose_name": "настройка рассылки",
                "verbose_name_plural": "настройки рассылок",
            },
        ),
    ]
